id: eb2811c0df6949b184e8bf10fb9cb20d
title: Toh_70-The_Sutra_of_the_Question_of_Subahu-v1
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-043-007
  eft-text-version: 1.1.10 2020
